version: 2.1
# this allows you to use CircleCI's dynamic configuration feature
setup: true
orbs:
  # orgs contain basc recipes and reproducible actions (install node, aws, etc.)
  node: circleci/node@5.0.2
  eb: circleci/aws-elastic-beanstalk@2.0.1
  aws-cli: circleci/aws-cli@3.1.1
  # different jobs are calles later in the workflows sections
jobs:
    build-and-deploy:
        docker:
        - image: 'cimg/base:stable'
        steps:
        - node/install:
            node-version: '16.13.2' 
        - checkout
        - aws-cli/setup
        - eb/setup
    frontend:
        # Use root level package.json to install dependencies in the frontend app
        - run:
            name: Install Front-End Dependencies
            command: npm run frontend:install
        # TODO: Lint the frontend
        - run:
            name: Front-End Lint
            command: npm run frontend:lint
        # TODO: Build the frontend app
        - run:
            name: Front-End Build
            command: npm run frontend:build
        # TODO: Start the frontend app
        - run:
            name: Front-End Start
            command: npm run frontend:start
        # TODO: Deploy the frontend app
        - run:
            name: Front-End Deploy
            command: npm run frontend:deploy
    backend:
        # TODO: Install dependencies in the the backend API          
        - run:
            name: Install backend Dependencies
            command: npm run backend:install
        # TODO: Build the backend API      
        - run:
            name: backend Build
            command: npm run backend:build
        # TODO: Start the backend API      
        - run:
            name: backend Start
            command: npm run backend:start
        # TODO: Deploy the backend API      
        - run:
            name: backend Deploy
            command: npm run backend:deploy
workflows:
    jobs:
        - build_and_deploy
        - frontend
        - backend
filters:
    branches:
      only:
      - main       